# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "nodejs_20"]

[phases.install]
cmds = [
    "npm install",
    "pip3 install -r requirements.txt"
]

[phases.build]
cmds = []

[start]
cmd = "bash start.sh"
